### ISSUE TITLE
Is it possible to consider requests with 302 response code successful?

### ISSUE THREAD

**Issue by minhdanh** [keen/pingpong#58]
I just need to check whether some of my apps are returning 5xx response code or not. 3xx is fine. Can that be achieved with pingpong?

**Comment by josephwegner** [comment]
Hey @minhdanh -

Are you seeing 302s as unsuccessful? It's been awhile since I've touched the Pingpong source, but looking at the code it _seems_ like 302s should count as successful.

Check out this code block: https://github.com/keen/pingpong/blob/c7f6ff4e787325d3ccfd5bd4ba00b9c3f75c5ab0/lib/eventmachine_check_runner.rb#L59-L62

Is that not what you're seeing?
